/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "background": "#faf9f5",
        "primary-container": "#ffd700",
        "on-surface": "#1b1c1a",
        "outline-variant": "#d0c6ab",
        "secondary-container": "#d4ed91",
        "on-primary": "#ffffff",
        "surface-container-low": "#f4f4f0",
        "primary": "#705d00",
        "outline": "#7e775f",
        "on-primary-container": "#705e00",
        "inverse-surface": "#2f312e",
        "primary-fixed-dim": "#e9c400",
        "secondary-fixed-dim": "#b8d078",
        "secondary-fixed": "#d4ed91",
        "on-primary-fixed": "#221b00",
        "on-background": "#1b1c1a",
        "tertiary": "#5e5e5e",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffe16d",
        "secondary": "#526619",
        "inverse-primary": "#e9c400",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e3e2df",
        "on-surface-variant": "#4d4732",
        "on-secondary": "#ffffff",
        "surface-variant": "#e3e2df",
        "error": "#ba1a1a",
        "surface-container": "#efeeea",
        "surface-dim": "#dbdad6",
        "surface": "#faf9f5",
        "on-secondary-container": "#576c1f",
        "surface-container-high": "#e9e8e4",
        "surface-bright": "#faf9f5",
        "on-error-container": "#93000a",
        "tertiary-container": "#dadada",
        "secondary-container-dark": "#d4ed91",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      boxShadow: {
        "neo": "4px 4px 0px 0px rgba(0,0,0,1)",
        "neo-lg": "6px 6px 0px 0px rgba(0,0,0,1)",
        "neo-xl": "8px 8px 0px 0px rgba(0,0,0,1)",
      }
    },
  },
  plugins: [],
}